default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: WARNING
  pool: 5
  database: react_playground_development

development:
  <<: *default
  database: react_playground_development

test:
  <<: *default
  database: react_playground_test

production:
  <<: *default
  database: react_playground_production
