# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6176a64dc62907e55e88df62ec7583e139a80ad012b58029c62bd393663baae69ea4372f27e11920a0104a49d6a43ca8c8577ccd708ada23546cfeb5261a2d81

test:
  secret_key_base: 6b998a7443014464c7ebe8506a4cd7d64750813e32420ff9d2dae66246eb53d7de306b264cdbf91e792ff6ed16bfc8e270e1e7cd91571e172e92bb043c17c7d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
